name: Spell-Check
# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  spell-check:
    # Name the Job
    name: Check spelling in the docs
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check spelling
        uses: check-spelling/check-spelling@0.0.16-alpha
        with:
          # Container for spelling configuration
          bucket:  ./
          # Folder/Branch within bucket containing spelling configuration
          project: ./
          # Debug
          debug: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
